# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - NETBOX-CEMIG

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://acrhubcemigprod.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_e333ac723d824ac5be9ae74065127469 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e45272f7af684d078b5e1245cb6e084a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: acrhubcemigprod.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e333ac723d824ac5be9ae74065127469 }}/netbox:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'NETBOX-CEMIG'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9f4f8f7985884af89c5c276448af21b8 }}
        images: 'acrhubcemigprod.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e333ac723d824ac5be9ae74065127469 }}/netbox:${{ github.sha }}'